version: "3.4"

services:  
  fastapi:
    build:
      context: src/
    ports:
      - "7777:7777"
    env_file:
      - .env
    networks:
      - app_network
  


volumes:
  redis:

networks:
  app_network:
