from abc import ABC


class AbstractCore(ABC):
    def __init__(self, **kwargs): ...
    async def get_session(self): ...
    async def get(self, url, params): ...
    async def post(self, url, params, body): ...
    async def put(self, url, params, body): ...
    async def delete(self, url, params, body): ...
    async def add_to_header(self, key, value): ...


class AbstractCrawler(ABC):
    def __init__(self):
        self.core = ...

    async def execute(self, url, params, body, page_num, method): ...
    async def authorize(self): ...
